Repository codesquad-member-2020/baseball-05, pull requests merged in 2020-05, with the labels that each got.

#10 경기 목록 화면의 뷰를 구성하였습니다.
  iOS/.gitignore
  iOS/BaseballGame/BaseballGame.xcodeproj/project.pbxproj
  iOS/BaseballGame/BaseballGame.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  iOS/BaseballGame/BaseballGame.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  iOS/BaseballGame/BaseballGame/AppDelegate.swift
  iOS/BaseballGame/BaseballGame/Assets.xcassets/AppIcon.appiconset/Contents.json
  iOS/BaseballGame/BaseballGame/Assets.xcassets/Contents.json
  iOS/BaseballGame/BaseballGame/Assets.xcassets/baseball.imageset/Contents.json
  iOS/BaseballGame/BaseballGame/Assets.xcassets/baseball.imageset/baseball.png
  iOS/BaseballGame/BaseballGame/Base.lproj/LaunchScreen.storyboard
  iOS/BaseballGame/BaseballGame/Base.lproj/Main.storyboard
  iOS/BaseballGame/BaseballGame/GameListViewController.swift
  iOS/BaseballGame/BaseballGame/Info.plist
  iOS/BaseballGame/BaseballGame/SceneDelegate.swift
  iOS/BaseballGame/BaseballGame/ViewModels/GameListViewModel.swift
  iOS/BaseballGame/BaseballGame/ViewModels/VersusViewModel.swift
  iOS/BaseballGame/BaseballGame/Views/GameInfoLabel.swift
  iOS/BaseballGame/BaseballGame/Views/GameInfoStackView.swift
  iOS/BaseballGame/BaseballGame/Views/GameInfoView.swift
  iOS/BaseballGame/BaseballGame/Views/TitleLabel.swift
  iOS/BaseballGame/BaseballGame/Views/VersusLabel.swift
  iOS/BaseballGame/BaseballGameTests/BaseballGameTests.swift
  iOS/BaseballGame/BaseballGameTests/Info.plist
  iOS/BaseballGame/BaseballGameUITests/BaseballGameUITests.swift
  iOS/BaseballGame/BaseballGameUITests/Info.plist
Labels: JK, enhancement

#12 [FE] 팀선택 화면 view 구성
  FE/.eslintrc.js
  FE/README.md
  FE/babel.config.js
  FE/jsconfig.json
  FE/package-lock.json
  FE/package.json
  FE/public/favicon.ico
  FE/public/index.html
  FE/src/App.vue
  FE/src/assets/mockTeamData.json
  FE/src/components/TeamComponent.vue
  FE/src/main.js
  FE/src/routes/index.js
  FE/src/views/SelectTeamView.vue
  FE/vue.config.js
Labels: FE

#14 게임 진행 화면 view 구성
  FE/src/App.vue
  FE/src/components/MainScoreComponent.vue
  FE/src/components/TeamComponent.vue
  FE/src/main.js
  FE/src/store/index.js
  FE/src/views/GameView.vue
  FE/src/views/LoginView.vue
  FE/src/views/SelectTeamView.vue
Labels: FE

#16 [FE] 경기중인 선수 컴포넌트 생성
  FE/src/components/PlayerComponent.vue
  FE/src/store/index.js
  FE/src/views/GameView.vue
Labels: FE

#19 Feature be/issue 8
  BE/.gitignore
  BE/.idea/.name
  BE/.idea/compiler.xml
  BE/.idea/dataSources.xml
  BE/.idea/jarRepositories.xml
  BE/.idea/misc.xml
  BE/.idea/vcs.xml
  BE/HELP.md
  BE/build.gradle
  BE/gradle/wrapper/gradle-wrapper.jar
  BE/gradle/wrapper/gradle-wrapper.properties
  BE/gradlew
  BE/gradlew.bat
  BE/settings.gradle
  BE/src/main/java/com/codesquad/baseball05/Baseball05Application.java
  BE/src/main/java/com/codesquad/baseball05/domain/GameStatusDTO.java
  BE/src/main/java/com/codesquad/baseball05/domain/Inning.java
  BE/src/main/java/com/codesquad/baseball05/domain/Plate.java
  BE/src/main/java/com/codesquad/baseball05/domain/Player.java
  BE/src/main/java/com/codesquad/baseball05/domain/Round.java
  BE/src/main/java/com/codesquad/baseball05/domain/Team.java
  BE/src/main/java/com/codesquad/baseball05/ui/MatchTable.java
  BE/src/main/java/com/codesquad/baseball05/ui/MockupController.java
  BE/src/main/java/com/codesquad/baseball05/ui/Response.java
  BE/src/main/java/com/codesquad/baseball05/ui/RosterBoard.java
  BE/src/main/java/com/codesquad/baseball05/ui/RoundRecordDto.java
  BE/src/main/java/com/codesquad/baseball05/ui/ScoreBoardDto.java
  BE/src/main/resources/application.properties
  BE/src/test/java/com/codesquad/baseball05/Baseball05ApplicationTests.java
Labels: BE

#20 [BE #18] DB 데이터 입력
  BE/.idea/codeStyles/codeStyleConfig.xml
  BE/.idea/dataSources.xml
  BE/.idea/sqldialects.xml
  BE/src/main/resources/data.sql
  BE/src/main/resources/schema.sql
Labels: BE

#22 [FE] GameBoard Component 생성
  FE/src/App.vue
  FE/src/assets/bg.jpg
  FE/src/components/GameBoardComponent.vue
  FE/src/components/TeamComponent.vue
Labels: FE

#24 [FE] GameLogComponent 생성
  FE/src/App.vue
  FE/src/components/GameLogComponent.vue
  FE/src/store/index.js
  FE/src/views/GameView.vue
Labels: FE

#26 [BE #21] Entity 구현
  BE/src/main/java/com/codesquad/baseball05/domain/GameStatusDTO.java
  BE/src/main/java/com/codesquad/baseball05/domain/Inning.java
  BE/src/main/java/com/codesquad/baseball05/domain/Plate.java
  BE/src/main/java/com/codesquad/baseball05/domain/Player.java
  BE/src/main/java/com/codesquad/baseball05/domain/Round.java
  BE/src/main/java/com/codesquad/baseball05/domain/Team.java
  BE/src/main/java/com/codesquad/baseball05/domain/entity/Game.java
  BE/src/main/java/com/codesquad/baseball05/domain/entity/Half.java
  BE/src/main/java/com/codesquad/baseball05/domain/entity/Inning.java
  BE/src/main/java/com/codesquad/baseball05/domain/entity/MatchTable.java
  BE/src/main/java/com/codesquad/baseball05/domain/entity/Plate.java
  BE/src/main/java/com/codesquad/baseball05/domain/entity/Player.java
  BE/src/main/java/com/codesquad/baseball05/domain/entity/Record.java
  BE/src/main/java/com/codesquad/baseball05/domain/entity/Round.java
  BE/src/main/java/com/codesquad/baseball05/domain/entity/Team.java
  BE/src/main/java/com/codesquad/baseball05/ui/MockupController.java
Labels: BE

#30 [FE] 경기 목록 API 연동 작업
  FE/.env
  FE/.env.development
  FE/src/api/common/interceptors.js
  FE/src/api/game.js
  FE/src/api/index.js
  FE/src/components/TeamComponent.vue
  FE/src/store/index.js
Labels: FE

#31 [iOS][#11]게임 기록화면에 대해 서버 연동하였습니다.
  iOS/BaseballGame/BaseballGame.xcodeproj/project.pbxproj
  iOS/BaseballGame/BaseballGame/Base.lproj/Main.storyboard
  iOS/BaseballGame/BaseballGame/GameListViewController.swift
  iOS/BaseballGame/BaseballGame/Info.plist
  iOS/BaseballGame/BaseballGame/Models/GameRoom.swift
  iOS/BaseballGame/BaseballGame/Networks/DataExtensions.swift
  iOS/BaseballGame/BaseballGame/Networks/Mocks/MockGameRoomSuccess.swift
  iOS/BaseballGame/BaseballGame/Networks/NetworkDispatcher.swift
  iOS/BaseballGame/BaseballGame/Networks/NetworkTask.swift
  iOS/BaseballGame/BaseballGame/Networks/Request.swift
  iOS/BaseballGame/BaseballGame/Networks/StubDatas/TeamInfoSuccessStub.json
  iOS/BaseballGame/BaseballGame/Usecases/GameRoomUseCase.swift
  iOS/BaseballGame/BaseballGame/ViewControllers/GameRoomViewController.swift
  iOS/BaseballGame/BaseballGame/ViewModels/GameListViewModel.swift
  iOS/BaseballGame/BaseballGame/ViewModels/GameRoom/GameRoomViewModel.swift
  iOS/BaseballGame/BaseballGame/ViewModels/GameRoom/GameRoomViewModels.swift
  iOS/BaseballGame/BaseballGame/ViewModels/ViewModelBinding.swift
  iOS/BaseballGame/BaseballGame/Views/GameInfoStackView.swift
  iOS/BaseballGame/BaseballGame/Views/GameInfoView.swift
  iOS/BaseballGame/BaseballGame/Views/GameRoom/GameRoomCell.swift
  iOS/BaseballGame/BaseballGame/Views/GameRoom/GameRoomCollectionView.swift
  iOS/BaseballGame/BaseballGame/Views/GameRoom/GameRoomLabel.swift
  iOS/BaseballGame/BaseballGame/Views/ReusableView.swift
  iOS/BaseballGame/BaseballGame/Views/TitleLabel.swift
  iOS/BaseballGame/BaseballGame/Views/VersusLabel.swift
  iOS/BaseballGame/BaseballGameTests/CodableTests.swift
  iOS/BaseballGame/BaseballGameTests/JsonDataTests.swift
  iOS/BaseballGame/BaseballGameTests/UseCaseTests.swift
Labels: JK

#33 [iOS][#32] 메인화면과 로그인 화면을 만들었습니다.
  iOS/BaseballGame/BaseballGame.xcodeproj/project.pbxproj
  iOS/BaseballGame/BaseballGame/Assets.xcassets/baseball.imageset/baseball.png
  iOS/BaseballGame/BaseballGame/Assets.xcassets/batter.imageset/Contents.json
  iOS/BaseballGame/BaseballGame/Assets.xcassets/batter.imageset/batter.png
  iOS/BaseballGame/BaseballGame/Assets.xcassets/github.imageset/Contents.json
  iOS/BaseballGame/BaseballGame/Assets.xcassets/github.imageset/github.png
  iOS/BaseballGame/BaseballGame/Base.lproj/Main.storyboard
  iOS/BaseballGame/BaseballGame/Utils/UIColorExtension.swift
  iOS/BaseballGame/BaseballGame/ViewControllers/GameRoomViewController.swift
  iOS/BaseballGame/BaseballGame/ViewControllers/LoginViewController.swift
  iOS/BaseballGame/BaseballGame/ViewControllers/MainViewController.swift
  iOS/BaseballGame/BaseballGame/ViewModels/GameRoom/GameRoomViewModels.swift
  iOS/BaseballGame/BaseballGame/Views/BorderedButton.swift
  iOS/BaseballGame/BaseballGame/Views/GameRoom/GameRoomCollectionView.swift
  iOS/BaseballGame/BaseballGame/Views/GameRoom/PrevButton.swift
  iOS/BaseballGame/BaseballGame/Views/OauthLoginButton.swift
  iOS/BaseballGame/BaseballGame/Views/TitleLabel.swift
Labels: JK

#37 [FE] NotFound 페이지 생성
  FE/src/routes/index.js
  FE/src/views/NotFoundPage.vue
Labels: FE

#39 [iOS][#35] 게임 진행 화면과 게임 스코어 화면의 공통된 뷰들을 만들었습니다.
  iOS/BaseballGame/BaseballGame.xcodeproj/project.pbxproj
  iOS/BaseballGame/BaseballGame/Base.lproj/Main.storyboard
  iOS/BaseballGame/BaseballGame/ViewControllers/GameRoomViewController.swift
  iOS/BaseballGame/BaseballGame/ViewControllers/IdentifiableViewController.swift
  iOS/BaseballGame/BaseballGame/ViewControllers/LoginViewController.swift
  iOS/BaseballGame/BaseballGame/ViewControllers/MainViewController.swift
  iOS/BaseballGame/BaseballGame/ViewControllers/PlayViewController.swift
  iOS/BaseballGame/BaseballGame/ViewControllers/ScoresViewController.swift
  iOS/BaseballGame/BaseballGame/Views/Game/ScoreView.swift
  iOS/BaseballGame/BaseballGame/Views/Game/ScoreView.xib
  iOS/BaseballGame/BaseballGame/Views/Game/TitleView.swift
  iOS/BaseballGame/BaseballGame/Views/Game/TitleView.xib
  iOS/BaseballGame/BaseballGame/Views/GameRoom/GameRoomCell.swift
  iOS/BaseballGame/BaseballGame/Views/GameRoom/PrevButton.swift
  iOS/BaseballGame/BaseballGame/Views/IdentifiableView.swift
  iOS/BaseballGame/BaseballGame/Views/ReusableView.swift
Labels: enhancement

#41 [iOS][#5] 게임 진행화면 뷰를 구성하였습니다.
  iOS/BaseballGame/BaseballGame.xcodeproj/project.pbxproj
  iOS/BaseballGame/BaseballGame/Base.lproj/Main.storyboard
  iOS/BaseballGame/BaseballGame/Views/Game/Play/BatterInfoCell.swift
  iOS/BaseballGame/BaseballGame/Views/Game/Play/BoardLabel.swift
  iOS/BaseballGame/BaseballGame/Views/Game/Play/BoardView.swift
  iOS/BaseballGame/BaseballGame/Views/Game/Play/CountView.swift
  iOS/BaseballGame/BaseballGame/Views/Game/Play/CurrentPlayerCell.swift
  iOS/BaseballGame/BaseballGame/Views/Game/Play/OrderLabel.swift
  iOS/BaseballGame/BaseballGame/Views/Game/Play/OrderView.swift
  iOS/BaseballGame/BaseballGame/Views/Game/Play/PitchButton.swift
  iOS/BaseballGame/BaseballGame/Views/Game/Play/PlayTableLabel.swift
  iOS/BaseballGame/BaseballGame/Views/Game/Play/SBOView.swift
  iOS/BaseballGame/BaseballGame/Views/Game/Play/SBOView.xib
  iOS/BaseballGame/BaseballGame/Views/Game/Play/SBOsView.swift
  iOS/BaseballGame/BaseballGame/Views/Game/ScoreView.swift
  iOS/BaseballGame/BaseballGame/Views/Game/ScoreView.xib
  iOS/BaseballGame/BaseballGame/Views/GameRoom/PrevButton.swift
Labels: JK

#42 [FE] 상세점수, 선수명단 팝업 컴포넌트 생성
  FE/src/App.vue
  FE/src/api/game.js
  FE/src/assets/12.png
  FE/src/assets/ground.jpg
  FE/src/components/Game/GameBoardComponent.vue
  FE/src/components/Game/GameLogComponent.vue
  FE/src/components/Game/MainScoreComponent.vue
  FE/src/components/Game/PlayerComponent.vue
  FE/src/components/Main/TeamComponent.vue
  FE/src/components/StatusBoard/PlayerInfoComponent.vue
  FE/src/components/StatusBoard/ScoreInfoComponent.vue
  FE/src/store/index.js
  FE/src/views/GameView.vue
  FE/src/views/LoginView.vue
  FE/src/views/SelectTeamView.vue
  FE/vue.config.js
Labels: FE

#52 [FE] GameView 기능구현
  FE/src/App.vue
  FE/src/api/game.js
  FE/src/assets/pitcher.png
  FE/src/components/Game/GameLogComponent.vue
  FE/src/components/GameStatusComponent.vue
  FE/src/components/GroundComponent.vue
  FE/src/components/Main/TeamComponent.vue
  FE/src/components/PlayButton.vue
  FE/src/components/Player.vue
  FE/src/components/ScoreComponent.vue
  FE/src/components/StatusBoard/PlayerInfoComponent.vue
  FE/src/components/StatusBoard/ScoreInfoComponent.vue
  FE/src/routes/index.js
  FE/src/store/index.js
  FE/src/views/GroundView.vue
Labels: FE

#55 [iOS][#46] 팀 선택하는 것에 대해 기능 구현 및 서버 연동하였고, User ID 데이터를 화면에 표시하였습니다.
  iOS/BaseballGame/BaseballGame.xcodeproj/project.pbxproj
  iOS/BaseballGame/BaseballGame/Models/GameRoom.swift
  iOS/BaseballGame/BaseballGame/Models/ResultResponse.swift
  iOS/BaseballGame/BaseballGame/Models/SelectingTeamName.swift
  iOS/BaseballGame/BaseballGame/Networks/Mocks/MockGameRoomsSuccess.swift
  iOS/BaseballGame/BaseballGame/Networks/Mocks/MockRoomIsFullFail.swift
  iOS/BaseballGame/BaseballGame/Networks/Mocks/MockRoomIsFullSuccess.swift
  iOS/BaseballGame/BaseballGame/Networks/Mocks/MockTeamSelectFail.swift
  iOS/BaseballGame/BaseballGame/Networks/Mocks/MockTeamSelectSuccess.swift
  iOS/BaseballGame/BaseballGame/Networks/StubDatas/GameRoomsSuccessStub.json
  iOS/BaseballGame/BaseballGame/Networks/StubDatas/RoomIsFullFailStub.json
  iOS/BaseballGame/BaseballGame/Networks/StubDatas/RoomIsFullSuccessStub.json
  iOS/BaseballGame/BaseballGame/Networks/StubDatas/TeamInfoSuccessStub.json
  iOS/BaseballGame/BaseballGame/Networks/StubDatas/TeamSelectFailStub.json
  iOS/BaseballGame/BaseballGame/Networks/StubDatas/TeamSelectSuccessStub.json
  iOS/BaseballGame/BaseballGame/Usecases/GameRoomUseCase.swift
  iOS/BaseballGame/BaseballGame/Usecases/RoomIsFullUseCase.swift
  iOS/BaseballGame/BaseballGame/Usecases/TeamSelectingUseCase.swift
  iOS/BaseballGame/BaseballGame/ViewControllers/GameRoomViewController.swift
  iOS/BaseballGame/BaseballGame/ViewModels/GameRoom/GameRoomViewModels.swift
  iOS/BaseballGame/BaseballGame/Views/GameRoom/GameRoomCell.swift
  iOS/BaseballGame/BaseballGame/Views/GameRoom/UserLabel.swift
  iOS/BaseballGame/BaseballGameTests/UseCaseTests.swift
Labels: JK

#58 Feature be/issue 25 solar
  BE/src/main/java/com/codesquad/baseball05/application/AdminService.java
  BE/src/main/java/com/codesquad/baseball05/application/BoardService.java
  BE/src/main/java/com/codesquad/baseball05/application/GameService.java
  BE/src/main/java/com/codesquad/baseball05/application/MatchService.java
  BE/src/main/java/com/codesquad/baseball05/domain/game/dto/HalfIdDTO.java
  BE/src/main/java/com/codesquad/baseball05/domain/game/dto/InningDTO.java
  BE/src/main/java/com/codesquad/baseball05/domain/game/dto/RosterBoardDTO.java
  BE/src/main/java/com/codesquad/baseball05/domain/game/dto/RoundRecordDTO.java
  BE/src/main/java/com/codesquad/baseball05/domain/game/dto/ScoreBoardDTO.java
  BE/src/main/java/com/codesquad/baseball05/domain/game/entity/Game.java
  BE/src/main/java/com/codesquad/baseball05/domain/game/entity/Half.java
  BE/src/main/java/com/codesquad/baseball05/domain/game/entity/Inning.java
  BE/src/main/java/com/codesquad/baseball05/domain/game/entity/Plate.java
  BE/src/main/java/com/codesquad/baseball05/domain/game/entity/Round.java
  BE/src/main/java/com/codesquad/baseball05/domain/matches/dto/MatchDTO.java
  BE/src/main/java/com/codesquad/baseball05/domain/team/entity/Team.java
  BE/src/main/java/com/codesquad/baseball05/infra/config/SimpleCorsFilter.java
  BE/src/main/java/com/codesquad/baseball05/infra/config/WebConfig.java
  BE/src/main/java/com/codesquad/baseball05/infra/dao/GameDAO.java
  BE/src/main/java/com/codesquad/baseball05/infra/dao/HalfDAO.java
  BE/src/main/java/com/codesquad/baseball05/infra/dao/MatchDAO.java
  BE/src/main/java/com/codesquad/baseball05/infra/dao/TeamDAO.java
  BE/src/main/java/com/codesquad/baseball05/infra/dao/UserDAO.java
  BE/src/main/java/com/codesquad/baseball05/ui/AdminController.java
  BE/src/main/java/com/codesquad/baseball05/ui/BoardController.java
  BE/src/main/java/com/codesquad/baseball05/ui/GameController.java
  BE/src/main/java/com/codesquad/baseball05/ui/GameMenuController.java
  BE/src/main/java/com/codesquad/baseball05/ui/ResponseBodyWrapper.java
  BE/src/main/resources/application.properties
  BE/src/main/resources/data.sql
  BE/src/main/resources/schema.sql
  BE/src/test/java/com/codesquad/baseball05/application/MatchServiceTest.java
  BE/src/test/java/com/codesquad/baseball05/infra/GameDAOTest.java
  BE/src/test/java/com/codesquad/baseball05/infra/TeamDAOTest.java
  BE/src/test/java/com/codesquad/baseball05/infra/UserDAOTest.java
Labels: BE

#59 [FE] 게임 매칭에 필요한 백엔드 통신
  FE/.env.production
  FE/package-lock.json
  FE/package.json
  FE/public/index.html
  FE/src/api/game.js
  FE/src/assets/BeanEater.svg
  FE/src/assets/hit.mp3
  FE/src/assets/loading.svg
  FE/src/assets/mario.mp3
  FE/src/assets/search.svg
  FE/src/assets/yep.mp3
  FE/src/components/Ball.vue
  FE/src/components/GameStatusComponent.vue
  FE/src/components/GroundComponent.vue
  FE/src/components/Main/GameStandbyComponent.vue
  FE/src/components/Main/TeamComponent.vue
  FE/src/components/PlayButton.vue
  FE/src/components/StatusBoard/PlayerInfoComponent.vue
  FE/src/components/StatusBoard/ScoreInfoComponent.vue
  FE/src/components/common/LoadingSpinner.vue
  FE/src/main.js
  FE/src/routes/index.js
  FE/src/store/index.js
  FE/src/views/GameStandByView.vue
  FE/src/views/GroundView.vue
  FE/src/views/LoginView.vue
  FE/src/views/SelectTeamView.vue
Labels: FE

#62 게임 진행화면 서버 연동하고 뷰를 개선하였습니다.
  iOS/BaseballGame/BaseballGame.xcodeproj/project.pbxproj
  iOS/BaseballGame/BaseballGame/Base.lproj/Main.storyboard
  iOS/BaseballGame/BaseballGame/Models/CurrentPlayer.swift
  iOS/BaseballGame/BaseballGame/Models/GameRoom.swift
  iOS/BaseballGame/BaseballGame/Models/PlayDataResponse.swift
  iOS/BaseballGame/BaseballGame/Models/RoundInfo.swift
  iOS/BaseballGame/BaseballGame/Models/RoundsResponse.swift
  iOS/BaseballGame/BaseballGame/Models/SBO.swift
  iOS/BaseballGame/BaseballGame/Models/UserInning.swift
  iOS/BaseballGame/BaseballGame/Networks/Mocks/MockRoundsSuccess.swift
  iOS/BaseballGame/BaseballGame/Networks/StubDatas/RoundsSuccessStub.json
  iOS/BaseballGame/BaseballGame/Usecases/PitchUseCase.swift
  iOS/BaseballGame/BaseballGame/Usecases/PlayUseCase.swift
  iOS/BaseballGame/BaseballGame/ViewControllers/GameRoomViewController.swift
  iOS/BaseballGame/BaseballGame/ViewControllers/PlayViewController.swift
  iOS/BaseballGame/BaseballGame/ViewModels/Play/BoardViewModel.swift
  iOS/BaseballGame/BaseballGame/ViewModels/Play/PlayTablesViewModel.swift
  iOS/BaseballGame/BaseballGame/ViewModels/Play/RoundInfoViewModel.swift
  iOS/BaseballGame/BaseballGame/ViewModels/Play/RoundInfoViewModels.swift
  iOS/BaseballGame/BaseballGame/ViewModels/Play/ScoreViewModel.swift
  iOS/BaseballGame/BaseballGame/Views/Game/Play/BoardView.swift
  iOS/BaseballGame/BaseballGame/Views/Game/Play/BoardView.xib
  iOS/BaseballGame/BaseballGame/Views/Game/Play/CurrentPlayerCell.swift
  iOS/BaseballGame/BaseballGame/Views/Game/Play/OrderLabel.swift
  iOS/BaseballGame/BaseballGame/Views/Game/Play/OrderView.swift
  iOS/BaseballGame/BaseballGame/Views/Game/Play/PitchButton.swift
  iOS/BaseballGame/BaseballGame/Views/Game/Play/RoundInfoCell.swift
  iOS/BaseballGame/BaseballGame/Views/Game/Play/SBOView.swift
  iOS/BaseballGame/BaseballGame/Views/Game/Play/SBOView.xib
  iOS/BaseballGame/BaseballGame/Views/Game/Play/SBOsView.swift
  iOS/BaseballGame/BaseballGame/Views/Game/Play/SBOsView.xib
  iOS/BaseballGame/BaseballGame/Views/GameRoom/GameRoomCell.swift
  iOS/BaseballGame/BaseballGameTests/CodableTests.swift
  iOS/BaseballGame/BaseballGameTests/UseCaseTests.swift
Labels: JK

#64 [iOS][#49] 야구장 그라운드 뷰를 구현하였습니다.
  iOS/BaseballGame/BaseballGame.xcodeproj/project.pbxproj
  iOS/BaseballGame/BaseballGame/Utils/UIColorExtension.swift
  iOS/BaseballGame/BaseballGame/Views/Game/Play/BoardView.swift
  iOS/BaseballGame/BaseballGame/Views/Game/Play/GroundView.swift
  iOS/BaseballGame/BaseballGame/Views/Game/Play/HomeBase.swift
  iOS/BaseballGame/BaseballGame/Views/Game/Play/HomeView.swift
  iOS/BaseballGame/BaseballGame/Views/Game/Play/RhombusView.swift
Labels: JK

#66 user 로그인 기능 구현
  BE/src/main/java/com/codesquad/baseball05/application/GameService.java
  BE/src/main/java/com/codesquad/baseball05/application/UserService.java
  BE/src/main/java/com/codesquad/baseball05/infra/dao/UserDAO.java
  BE/src/main/java/com/codesquad/baseball05/infra/exception/GlobalExceptionHandler.java
  BE/src/main/java/com/codesquad/baseball05/infra/exception/NotFoundUserException.java
  BE/src/main/java/com/codesquad/baseball05/ui/GameController.java
  BE/src/main/java/com/codesquad/baseball05/ui/UserController.java
Labels: BE
